# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7436b5ce0c7a6f78bbe88a6d88983e5"
name = "volume-discount"
handle = "volume-discount-58"
application_url = "https://humane-fly-tops.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "functions-and-stuff.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://humane-fly-tops.ngrok-free.app/auth/callback",
  "https://humane-fly-tops.ngrok-free.app/auth/shopify/callback",
  "https://humane-fly-tops.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
